### ISSUE TITLE
Configurable `OrientationAccuracy` Default Value in `config.sample.yaml`

### ISSUE THREAD

**Issue by camrex** [camrex/rmi-360-workflow-pyt#10]
# Feature Request: Configurable `OrientationAccuracy` Default Value in `config.sample.yaml`

**Summary:**  
With the release of ArcGIS Pro 3.5, a new OID attribute, `OrientationAccuracy`, was added. This field has been included as a Standard field in `esri_oid_fields_registry.yaml` with its default value set per ESRI documentation. To improve flexibility, it would be beneficial to allow users to define the default value for `OrientationAccuracy` in `config.sample.yaml`.

---

## Background

- **ArcGIS Pro 3.5** introduced the `OrientationAccuracy` field as part of its OID attributes.
- The field is now present in our `esri_oid_fields_registry.yaml`, using the default value specified by ESRI.
- At present, users cannot override this value via configuration—customizing it requires editing core files, complicating upgrades and configuration management.

---

## Proposed Enhancement

- **Expose the default value of `OrientationAccuracy` as a configurable option in `config.sample.yaml`.**
  - The workflow should reference this value during OID field initialization.
  - If present, the value specified in the user's configuration should override the hardcoded default in `esri_oid_fields_registry.yaml`.
  - Add documentation/comments in `config.sample.yaml` to explain this setting, including expected value type/range per ESRI documentation.

---

## Benefits

- **Greater flexibility:** Users can define project-specific defaults without modifying the registry file.
- **Easier upgrades:** Configuration-driven design reduces the risk of losing customizations during project updates.
- **Transparency:** Clearer documentation and user control over OID attribute initialization.

---

## Example (`config.sample.yaml`)

```yaml
# OID Fields Custom Defaults
oid_fields:
  OrientationAccuracy: "5;10;5;5;5;0;0;1"  
  # String (semicolon-delimited) of up to eight values, in this order:
  # Camera XY; Camera Z; Heading; Pitch; Roll; Near distance; Far distance; Elevation
  # Distances are in meters unless the coordinate system is in feet; angles are in degrees.
  # Example (vehicle mounted consumer camera): "5;10;5;5;5;0;0;1"
  # Example (aerial triangulation): "0.01;0.02;0.001;0.001;0.001;0;0;1"
  # If a value is unknown, it may be excluded (e.g., "10;20" for GPS RMS accuracy in XY/Z)
```

---

## Additional Notes

- The `OrientationAccuracy` value **must** be a string of up to eight semicolon-delimited values, as defined by ESRI.
- Values represent:  
  `Camera XY; Camera Z; Heading; Pitch; Roll; Near distance; Far distance; Elevation`
- Distances should be in meters (unless your coordinate system uses feet); angles are in degrees.
- If a value is unknown, you can exclude it (e.g., `"10;20"`), but this may overstate the accuracy.
- Please refer to the [official ESRI documentation](https://pro.arcgis.com/) for more context on recommended values and usage.

---

**Related Files:**  
- `esri_oid_fields_registry.yaml`  
- `config.sample.yaml`  
- (Any relevant code locations for OID field initialization)

---

**Thank you for considering this feature request!**
